spring.application.name=demo

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/biblioteca_cve?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.profiles.include=local


gemini.api.key=${GEMINI_API_KEY}


spring.web.resources.cache.period=31536000